/*

 TESTMAP2.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 30 x 30
   Tile set      : D:\Code\GB\The-last-Slime\Tiles_docs\Test_bkg.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define testMap2Width 30
#define testMap2Height 30
#define testMap2Bank 0

extern unsigned char testMap2[];

/* End of TESTMAP2.H */
